/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_casia_cripac_isee_pedestrian_tracking_NativeTracker2000 */

#ifndef _Included_org_casia_cripac_isee_pedestrian_tracking_NativeTracker2000
#define _Included_org_casia_cripac_isee_pedestrian_tracking_NativeTracker2000
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     org_casia_cripac_isee_pedestrian_tracking_NativeTracker2000
 * Method:    nativeTrack
 * Signature: (III[B[[B)[Lorg/casia/cripac/isee/pedestrian/tracking/Track;
 */
JNIEXPORT jobjectArray JNICALL Java_org_casia_cripac_isee_pedestrian_tracking_NativeTracker2000_nativeTrack(
		JNIEnv *, jobject, jint, jint, jint, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
