/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_vpe_ctrl_MonitorThread */

#ifndef _Included_org_cripac_isee_vpe_ctrl_MonitorThread
#define _Included_org_cripac_isee_vpe_ctrl_MonitorThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_cripac_isee_vpe_ctrl_MonitorThread_MIN_PRIORITY
#define org_cripac_isee_vpe_ctrl_MonitorThread_MIN_PRIORITY 1L
#undef org_cripac_isee_vpe_ctrl_MonitorThread_NORM_PRIORITY
#define org_cripac_isee_vpe_ctrl_MonitorThread_NORM_PRIORITY 5L
#undef org_cripac_isee_vpe_ctrl_MonitorThread_MAX_PRIORITY
#define org_cripac_isee_vpe_ctrl_MonitorThread_MAX_PRIORITY 10L
/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    initNVML
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_initNVML
    (JNIEnv *, jobject);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getDeviceCount
    (JNIEnv *, jobject);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getFanSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getFanSpeed
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getUtilizationRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getUtilizationRate
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getFreeMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getFreeMemory
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getTotalMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getTotalMemory
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getUsedMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getUsedMemory
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getTemperature
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getTemperature
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getSlowDownTemperatureThreshold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getSlowDownTemperatureThreshold
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getShutdownTemperatureThreshold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getShutdownTemperatureThreshold
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getPowerLimit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getPowerLimit
    (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_MonitorThread
 * Method:    getPowerUsage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_MonitorThread_getPowerUsage
    (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
